- name: Create Pull Request
  id: cpr
  uses: peter-evans/create-pull-request@v3
  with:
    token: ${{ secrets.TOKEN }}
    branch: terraform-plan-$(date +%s)
    commit-message: "Terraform plan for $(date +%F_%T)"
    title: "Terraform Plan for $(date +%F_%T)"
    body: |
      **Terraform Plan**
      ```
      $(cat plan.txt)
      ```
- name: Wait for review
  id: review
  uses: actions/github-script@v4
  with:
    script: |
      const [owner, repo] = process.env.GITHUB_REPOSITORY.split("/");
      const { data: reviews } = await github.pulls.listReviews({
        owner,
        repo,
        pull_number: context.payload.pull_request.number
      });
      const approved = reviews.some(review => review.state === "APPROVED");
      return {approved};
  env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
- name: terraform deployment
  if: steps.review.outputs.approved == 'true'
  run: terraform apply